apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: crewcash-postgres
data:
  init.sql: |
    CREATE DATABASE crewcashdb_wallet;
    CREATE DATABASE crewcashdb_budget;
    CREATE DATABASE crewcashdb_sharing;
    CREATE DATABASE crewcashdb_payment;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewcash-postgres
  labels:
    db: crewcash-postgres
spec:
  selector:
    matchLabels:
      db: crewcash-postgres
  template:
    metadata:
      labels:
        db: crewcash-postgres
    spec:
      containers:
        - name: crewcash-postgres
          image: postgres:14.12
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: crewcash-postgres
  labels:
    db: crewcash-postgres
spec:
  type: ClusterIP
  selector:
    db: crewcash-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
