apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/crewcash/budget-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: budget-config

images:
- name: budget-service
  newName: ghcr.io/crewcash/budget-service
  newTag: 16d6b1d39a2c392338f1d3033e9162907f500101

replicas:
- count: 1
  name: budget-service
