apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-service
spec:
  template:
    spec:
      containers:
        - name: budget-service
          volumeMounts:
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
      volumes:
        - name: rabbitmq-credentials-volume
          secret:
            secretName: crewcash-rabbitmq-credentials
