apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/crewcash/edge-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-ingress.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application.yml
    name: edge-config

images:
  - name: edge-service
    newName: ghcr.io/crewcash/edge-service
    newTag: latest

replicas:
  - count: 1
    name: edge-service
