apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/crewcash/edge-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/crewcash/edge-service
  newTag: fb52f3f9ddc92e31a7ef9b9eed897d219cbc5ce4

replicas:
- count: 1
  name: edge-service
