apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/edge-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/myhabitquest/edge-service
  newTag: 1288990cc991c4ec1c7f06a90b042287644c04e0

replicas:
- count: 1
  name: edge-service
