apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/quest-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: quest-config

images:
- name: quest-service
  newName: ghcr.io/myhabitquest/quest-service
  newTag: b0e526ffefcbe501118caaced29b87203a8187f7

replicas:
- count: 2
  name: quest-service
