apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/quest-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: quest-config

images:
- name: quest-service
  newName: ghcr.io/myhabitquest/quest-service
  newTag: 4f79b12e389aa9a3ae7b3147ded7094986d1e2fc

replicas:
- count: 2
  name: quest-service
