apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/marketplace-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: marketplace-config

images:
- name: marketplace-service
  newName: ghcr.io/myhabitquest/marketplace-service
  newTag: 57a7f762d8691e11e574d3321ef08fc0eaab076d

replicas:
- count: 1
  name: marketplace-service
