apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-service
spec:
  template:
    spec:
      containers:
        - name: marketplace-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod