apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/crewcash/sharing-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application.yml
    name: sharing-config

images:
  - name: sharing-service
    newName: ghcr.io/crewcash/sharing-service
    newTag: latest

replicas:
  - count: 2
    name: sharing-service
