apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/crewcash/sharing-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: sharing-config

images:
- name: sharing-service
  newName: ghcr.io/crewcash/sharing-service
  newTag: ab4037cf1b718892019671bba2e1660c0aa6c1b7

replicas:
- count: 2
  name: sharing-service
