apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharing-service
spec:
  template:
    spec:
      containers:
        - name: sharing-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: crewcash-postgres-sharing-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret