apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/crewcash/template-project//k8s?ref=main

patches:
  - path: patch-resources.yml
#  - path: patch-volumes.yml

images:
  - name: template-project
    newName: ghcr.io/crewcash/template-project
    newTag: latest

replicas:
  - count: 1
    name: template-project  
