apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/crewcash/notification-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application.yml
    name: notification-config

images:
  - name: notification-service
    newName: ghcr.io/crewcash/notification-service
    newTag: latest

replicas:
  - count: 1
    name: notification-service
