apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/crewcash/notification-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: notification-config

images:
- name: notification-service
  newName: ghcr.io/crewcash/notification-service
  newTag: d55b26df4fe9ae62767db6f0f81fab247daf602f

replicas:
- count: 1
  name: notification-service
