apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/notification-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: notification-config

images:
- name: notification-service
  newName: ghcr.io/myhabitquest/notification-service
  newTag: 1b3c7c40345167f90d4f08fb73a814f413cd1bde

replicas:
- count: 1
  name: notification-service
