apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/myhabitquest/notification-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application.yml
  name: notification-config

images:
- name: notification-service
  newName: ghcr.io/myhabitquest/notification-service
  newTag: fd8e1e0577c2eb0ca59976f00a33fe16cf0d72df

replicas:
- count: 1
  name: notification-service
